catalogs:
  build:
    '@commitlint/cli': ^20.0.0
    '@commitlint/config-conventional': ^20.0.0
    '@nuxt/devtools': ^2.6.3
    '@nuxt/eslint': ^1.9.0
    '@nuxt/kit': ^4.0.0
    '@pinia/nuxt': ^0.11.2
    '@vite-pwa/nuxt': ^1.0.4
    '@vueuse/nuxt': ^13.9.0
    nuxt: ^4.1.2
    unplugin: ^2.3.5
    vite: ^7.0.4
  dev:
    '@antfu/eslint-config': ^5.4.1
    eslint: ^9.36.0
    eslint-plugin-format: ^1.0.2
    eslint-plugin-tailwindcss: 4.0.0-beta.0
    lint-staged: ^16.2.3
    simple-git-hooks: ^2.13.1
    tailwindcss: ^4.1.13
    typescript: ^5.9.2
    vue-tsc: ^3.1.0
  frontend:
    '@nuxt/ui': ^4.0.0
    '@vueuse/core': ^13.9.0
    pinia: ^3.0.3
    vue: ^3.5.22
    zod: ^4.1.11
  icons:
    '@iconify-json/carbon': ^1.2.13
    '@iconify-json/twemoji': ^1.2.4

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - simple-git-hooks
  - unrs-resolver
  - vue-demi
