packages: []

catalogs:
  build:
    '@commitlint/cli': ^19.8.1
    '@commitlint/config-conventional': ^19.8.1
    '@nuxt/devtools': ^2.6.3
    '@nuxt/eslint': ^1.9.0
    '@nuxt/kit': ^4.0.0
    '@pinia/nuxt': ^0.11.2
    '@vite-pwa/nuxt': ^1.0.4
    '@vueuse/nuxt': ^13.9.0
    husky: ^9.1.7
    nuxt: ^4.1.2
    unplugin: ^2.3.5
    vite: ^7.0.4
  dev:
    '@antfu/eslint-config': ^5.3.0
    eslint: ^9.35.0
    eslint-plugin-format: ^1.0.1
    eslint-plugin-tailwindcss: 4.0.0-beta.0
    typescript: ^5.9.2
    vue-tsc: ^3.0.7
  frontend:
    '@nuxt/ui-pro': ^3.3.4
    '@vueuse/core': ^13.9.0
    pinia: ^3.0.3
    vue: ^3.5.21
    zod: ^3.24.1
  icons:
    '@iconify-json/carbon': ^1.2.13
    '@iconify-json/twemoji': ^1.2.4

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver
  - vue-demi
